name: dozzle

services:
  dozzle:
    image: amir20/dozzle:v11@sha256:fa0eeeee9ce13db388eadb7d88ff33285b0a49cf551640f1fe6d408bf6acc5a7
    command: ["--no-analytics"]
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=dozzle"
      - "docktail.service.port=8080"
      - "docktail.service.service-port=443"
